// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cpp_seminribm_run
List cpp_seminribm_run(double horizon, unsigned long popSize, double R0, double latent_mean, double infectious_mean, int nE, int nI, unsigned long initInfectious, bool calc_WIW_Re, bool doExact, double timeStepTauLeap, unsigned int rnd_seed);
RcppExport SEXP _seminribm_cpp_seminribm_run(SEXP horizonSEXP, SEXP popSizeSEXP, SEXP R0SEXP, SEXP latent_meanSEXP, SEXP infectious_meanSEXP, SEXP nESEXP, SEXP nISEXP, SEXP initInfectiousSEXP, SEXP calc_WIW_ReSEXP, SEXP doExactSEXP, SEXP timeStepTauLeapSEXP, SEXP rnd_seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type horizon(horizonSEXP);
    Rcpp::traits::input_parameter< unsigned long >::type popSize(popSizeSEXP);
    Rcpp::traits::input_parameter< double >::type R0(R0SEXP);
    Rcpp::traits::input_parameter< double >::type latent_mean(latent_meanSEXP);
    Rcpp::traits::input_parameter< double >::type infectious_mean(infectious_meanSEXP);
    Rcpp::traits::input_parameter< int >::type nE(nESEXP);
    Rcpp::traits::input_parameter< int >::type nI(nISEXP);
    Rcpp::traits::input_parameter< unsigned long >::type initInfectious(initInfectiousSEXP);
    Rcpp::traits::input_parameter< bool >::type calc_WIW_Re(calc_WIW_ReSEXP);
    Rcpp::traits::input_parameter< bool >::type doExact(doExactSEXP);
    Rcpp::traits::input_parameter< double >::type timeStepTauLeap(timeStepTauLeapSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type rnd_seed(rnd_seedSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_seminribm_run(horizon, popSize, R0, latent_mean, infectious_mean, nE, nI, initInfectious, calc_WIW_Re, doExact, timeStepTauLeap, rnd_seed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_seminribm_cpp_seminribm_run", (DL_FUNC) &_seminribm_cpp_seminribm_run, 12},
    {NULL, NULL, 0}
};

RcppExport void R_init_seminribm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
