# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_seminribm_run <- function(horizon, popSize, R0, latent_mean, infectious_mean, nE, nI, initInfectious, calc_WIW_Re, doExact, timeStepTauLeap, rnd_seed) {
    .Call(`_seminribm_cpp_seminribm_run`, horizon, popSize, R0, latent_mean, infectious_mean, nE, nI, initInfectious, calc_WIW_Re, doExact, timeStepTauLeap, rnd_seed)
}

